tasks:
  - name: Packages
    command: |
      python3 -m pip install -U --user mkdocs-material
      export TZ='Europe/Berlin'

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
